version: '3'

services:
  casa-lite:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./output:/app/output
    restart: always
    environment:
      - FLASK_ENV=production
      - MAX_UPLOAD_SIZE=500
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s 