services:
  - type: web
    name: casa-lite
    env: python
    buildCommand: bash build.sh
    startCommand: gunicorn wsgi:app --log-file -
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: MAX_UPLOAD_SIZE
        value: "500"
    healthCheckPath: /
    disk:
      name: casa-lite-data
      mountPath: /app/uploads
      sizeGB: 1 